import { Home, Grid3X3, FileText, BarChart3, Edit3, Puzzle, MoreHorizontal } from "lucide-react";

export const menuContent: Record<string, React.ReactNode> = {
  Dashboard: <div className="text-7xl font-bold">Dashboard</div>,
  Analytics: <div className="text-7xl font-bold">Analytics</div>,
  Reports: <div className="text-7xl font-bold ">Reports</div>,
  "New Project": <div className="text-7xl font-bold">New Project</div>,
  "Invite Team": <div className="text-7xl font-bold ">Invite Team</div>,
  Settings: <div className="text-7xl font-bold ">Settings</div>,
  CRM: <div className="text-7xl font-bold">CRM</div>,
  "E-Commerce": <div className="text-7xl font-bold">E-Commerce</div>,
  "Project Manager": <div className="text-7xl font-bold ">Project Manager</div>,
  "Chat App": <div className="text-7xl font-bold ">Chat App</div>,
  "API Keys": <div className="text-7xl font-">API Keys</div>,
  Webhooks: <div className="text-7xl font-bold">Webhooks</div>,
  Plugins: <div className="text-7xl font-bold ">Plugins</div>,
  Login: <div className="text-7xl font-bold">Login</div>,
  Register: <div className="text-7xl font-bold">Register</div>,
  "Forgot Password": <div className="text-7xl font-bold">Forgot Password</div>,
  "404 Not Found": <div className="text-9xl font-bold text-red-500">404</div>,
  "500 Error": <div className="text-9xl font-bold text-red-600">500</div>,
  Maintenance: <div className="text-7xl font-bold text-yellow-600">Maintenance</div>,
  "Line Chart": <div className="text-7xl font-bold">Line Chart</div>,
  "Bar Chart": <div className="text-7xl font-bold">Bar Chart</div>,
  "Pie Chart": <div className="text-7xl font-bold">Pie Chart</div>,
  "Area Chart": <div className="text-7xl font-bold">Area Chart</div>,
  "Basic Table": <div className="text-7xl font-bold">Basic Table</div>,
  "Data Grid": <div className="text-7xl font-bold">Data Grid</div>,
  "Editable Table": <div className="text-7xl font-bold">Editable Table</div>,
  Buttons: <div className="text-7xl font-bold">Buttons</div>,
  Cards: <div className="text-7xl font-bold">Cards</div>,
  Modals: <div className="text-7xl font-bold">Modals</div>,
  Forms: <div className="text-7xl font-bold">Forms</div>,
  "Drag & Drop": <div className="text-7xl font-bold">Drag & Drop</div>,
  Charts: <div className="text-7xl font-bold">Charts</div>,
  Maps: <div className="text-7xl font-bold">Maps</div>,
  Calendar: <div className="text-7xl font-bold">Calendar</div>,
};
export  const mainApps = [
    { label: "Home", icon: Home },
    { label: "Applications", icon: Grid3X3 },
    { label: "Pages", icon: FileText },
    { label: "Tables Charts", icon: BarChart3 },
    { label: "Table Form", icon: Edit3 },
    { label: "UI Collection", icon: Puzzle },
    { label: "One Level ...", icon: MoreHorizontal },
  ];

 export const themeConfig = {
    light: {
      sidebarBg: "bg-white",
      headerBg: "bg-white",
      headerBorder: "border-gray-200",
      headerText: "text-gray-900",
      leftPanelBg: "bg-gray-50",
      rightPanelBg: "bg-white",
      textPrimary: "text-gray-900",
      textSecondary: "text-gray-600",
      hoverBg: "hover:bg-gray-100",
      activeBg: "bg-blue-100",
      activeText: "text-blue-700",
      activeBorder: "border-blue-500",
      groupTitle: "text-blue-600",
      groupTitleInactive: "text-gray-500",
    },
    dark: {
      sidebarBg: "bg-gray-900",
      headerBg: "bg-gray-800",
      headerBorder: "border-gray-700",
      headerText: "text-white",
      leftPanelBg: "bg-gray-900",
      rightPanelBg: "bg-gray-900",
      textPrimary: "text-white",
      textSecondary: "text-gray-400",
      hoverBg: "hover:bg-gray-800",
      activeBg: "bg-gray-700",
      activeText: "text-white",
      activeBorder: "border-gray-400",
      groupTitle: "text-gray-300",
      groupTitleInactive: "text-gray-500",
    },
    orange: {
      sidebarBg: "bg-orange-50",
      headerBg: "bg-white",
      headerBorder: "border-orange-200",
      headerText: "text-orange-900",
      leftPanelBg: "bg-orange-100",
      rightPanelBg: "bg-orange-50",
      textPrimary: "text-orange-900",
      textSecondary: "text-orange-700",
      hoverBg: "hover:bg-orange-100",
      activeBg: "bg-orange-200",
      activeText: "text-orange-800",
      activeBorder: "border-orange-500",
      groupTitle: "text-orange-700",
      groupTitleInactive: "text-orange-500",
    },
    blue: {
      sidebarBg: "bg-blue-50",
      headerBg: "bg-white",
      headerBorder: "border-blue-200",
      headerText: "text-blue-900",
      leftPanelBg: "bg-blue-100",
      rightPanelBg: "bg-blue-50",
      textPrimary: "text-blue-900",
      textSecondary: "text-blue-700",
      hoverBg: "hover:bg-blue-100",
      activeBg: "bg-blue-200",
      activeText: "text-blue-800",
      activeBorder: "border-blue-500",
      groupTitle: "text-blue-700",
      groupTitleInactive: "text-blue-500",
    },
    green: {
      sidebarBg: "bg-green-50",
      headerBg: "bg-white",
      headerBorder: "border-green-200",
      headerText: "text-green-900",
      leftPanelBg: "bg-green-100",
      rightPanelBg: "bg-green-50",
      textPrimary: "text-green-900",
      textSecondary: "text-green-700",
      hoverBg: "hover:bg-green-100",
      activeBg: "bg-green-200",
      activeText: "text-green-800",
      activeBorder: "border-green-500",
      groupTitle: "text-green-700",
      groupTitleInactive: "text-green-500",
    },
  };